package stepdefinitions;

import com.microsoft.playwright.APIResponse;
import com.microsoft.playwright.PlaywrightException;
import com.opencsv.exceptions.CsvValidationException;
import factory.DriverFactory;
import io.cucumber.datatable.DataTable;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.junit.Assert;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pages.Navigation;
import pages.admin.Accounts;
import pages.admin.Setup;
import pages.life.*;
import pages.studio.WorkspaceCreation;
import utils.*;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.file.Path;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

import static utils.CommonUtils.normalize;
import static utils.CommonUtils.normalizeObjectList;

public class LifeSteps {

    private static final Logger logger = LoggerFactory.getLogger(LifeSteps.class);
    static String campaignNameRandom;
    static String lineItemNameRandom;
    static String tacticNameRandom;
    static String dealNameRandom;
    static String dealIDRandom;
    static String url;
    static String username;
    static String password;
    static String npiName;
    static String npiNameEdited;
    static String templateNameRandom;
    static String dimensionName;
    static String metricName;
    static String newPixelName;
    static String pixelNameEdited;
    static String userType;
    List<Object> keyType = new ArrayList<>();
    List<Object> keyValues = new ArrayList<>();
    Map<String, Map<String, String>> keyValueMap = new LinkedHashMap<>();
    Map<String, List<String>> rulesMap = new LinkedHashMap<>();
    List<String> nameList = new ArrayList<>();
    List<String> capturedDetails = new ArrayList<>();
    List<String> itemList = new ArrayList<>();
    Map<String, List<String>> itemMap = new HashMap<>();
    Navigation navigation = new Navigation(DriverFactory.getPage());
    Campaigns campaigns = new Campaigns(DriverFactory.getPage());
    LineItemDetails lineItemDetails = new LineItemDetails(DriverFactory.getPage());
    TacticDetails tacticDetails = new TacticDetails(DriverFactory.getPage());
    TacticSettings tacticSettings = new TacticSettings(DriverFactory.getPage());
    TacticCreatives tacticCreatives = new TacticCreatives(DriverFactory.getPage());
    NPILists npiLists = new NPILists(DriverFactory.getPage());
    NPIStaticList npiStaticList = new NPIStaticList(DriverFactory.getPage());
    ReportTemplates reportTemplates = new ReportTemplates(DriverFactory.getPage());
    PMP pmp = new PMP(DriverFactory.getPage());
    NPISmartList npiSmartList = new NPISmartList(DriverFactory.getPage());
    CampaignDashboard campaignDashboard = new CampaignDashboard(DriverFactory.getPage());
    TargetingTemplate targetingTemplate = new TargetingTemplate(DriverFactory.getPage());
    CreateCreatives createCreatives = new CreateCreatives(DriverFactory.getPage());
    NPIAttributesList npiAttributesList = new NPIAttributesList(DriverFactory.getPage());
    NPIAutoImportedList npiAutoImportedList = new NPIAutoImportedList(DriverFactory.getPage());
    SharedList sharedList = new SharedList(DriverFactory.getPage());
    Pixels pixels = new Pixels(DriverFactory.getPage());
    RetargetingPixel retargetingPixel = new RetargetingPixel(DriverFactory.getPage());
    ConversionPixel conversionPixel = new ConversionPixel(DriverFactory.getPage());
    SmartPixel smartPixel = new SmartPixel(DriverFactory.getPage());
    BulkCreativeUpload bulkCreativeUpload = new BulkCreativeUpload(DriverFactory.getPage());
    RunReportPanel runReportPanel = new RunReportPanel(DriverFactory.getPage());
    Accounts accounts = new Accounts(DriverFactory.getPage());
    ScheduleReport scheduleReport = new ScheduleReport(DriverFactory.getPage());
    LineItemFlights lineItemFlights = new LineItemFlights(DriverFactory.getPage());
    CampaignSettings campaignSettings = new CampaignSettings(DriverFactory.getPage());
    WorkspaceCreation workspaceCreation = new WorkspaceCreation(DriverFactory.getPage());
    Setup setup = new Setup(DriverFactory.getPage());
    CuratedMarket curatedMarket = new CuratedMarket(DriverFactory.getPage());
    Constants constants = new Constants();
    ListSortingPage listSortingPage = new ListSortingPage(DriverFactory.getPage());
    utils.WaitUtility waitUtility = new utils.WaitUtility(DriverFactory.getPage());
    static String currentListType;
    static String notedRecordText;
    static int notedRecordIndex;
    static List<String> notedMultipleRecordTexts = new ArrayList<>();
    static String notedCreatedOnTimestamp;
    static String notedRowOnPage;
    int itemCount = 0;
    int totalListCount = 0;
    int flightStartDate = 0;
    int flightEndDate = 0;
    APIResponse response;
    boolean flag = false;
    String customFieldName;
    String uiCustomFieldName;
    BigDecimal campaignBaseBid;
    BigDecimal campaignMaxBid;
    BigDecimal campaignHighestBid;
    Path targetFilePath;
