Feature: Fetch data using MCP Tools by retrieving metadata, creating query and executing query using dimensions and metrics
  1. STG Token
  2. MCP Initialize
  3. MCP Tools List
  4. MCP Prompts List
  5. MCP Prompt Get
  6. MCP Tool Call - Looker Get Explore Metadata
  7. MCP Tool Call - Create Query
  8. MCP Tool Call - Execute Query

  @regression
  Scenario Outline: Validate AI-generated business analytics across diverse prompt inputs - "<USER_PROMPT>"
    Given I call the Token API using the API key for authentication with configuration:
      | Content-Type | application/x-www-form-urlencoded |
      | grant_type   | client_credentials                |
      | client_id    | platform-twenty-dpd               |
      | audience     | studio-api                        |
    Then Verify the Token API response status and presence of a valid access token
    When User initializes the MCP server using the access token with headers:
      | Content-Type | application/json                    |
      | Accept       | application/json, text/event-stream |
    Then Verify the MCP server initialization response is successful
    And User calls the MCP tool to create a query for the user prompt using dimensions and metrics with headers:
      | Content-Type    | application/json                     |
      | Accept          | application/json, text/event-stream  |
      | X-Account-Id    | <ACCOUNT_ID>                         |
      | X-Advertiser-Id | <ADVERTISER_ID>                      |
      | X-User-Id       | <USER_ID>                            |
      | Dimension       | <PROMPT_SPECIFIC_DIMENSIONS_METRICS> |
      | FilterLabel     | <FILTER_LABEL>                       |
      | FilterValue     | <FILTER_VALUE>                       |
      | Sort            | <SORT_BY>                            |
      | Limit           | <LIMIT>                              |
    Then Verify the query is created successfully and returns a query ID
    And User calls the MCP tool to execute the created query with headers:
      | Content-Type    | application/json                    |
      | Accept          | application/json, text/event-stream |
      | X-Account-Id    | <ACCOUNT_ID>                        |
      | X-Advertiser-Id | <ADVERTISER_ID>                     |
      | X-User-Id       | <USER_ID>                           |
    Then Verify the query execution response contains the retrieved data "<PROMPT_SPECIFIC_DIMENSIONS_METRICS>"
    Examples:
      | ACCOUNT_ID | ADVERTISER_ID | USER_ID | USER_PROMPT                                                                                                                          | PROMPT_SPECIFIC_DIMENSIONS_METRICS                                                                                                         | FILTER_LABEL                             | FILTER_VALUE              | SORT_BY                                           | LIMIT |
      | 561973     | 5590          | 69431   | What is the trend of Identified NPIs and Total Active Users by Day for the last 8 weeks, including a 7-day moving average?           | resolved_measures.distinct_npis, custom_measures_ga4.active_user_count_, hcp365_core.day                                                   | hcp365_core.day                          | 56 days ago for 56 days   | hcp365_core.day asc                               | 500   |
      | 561673     | 5586          | 69431   | Show NPI First Visits vs NPI Returning Visits by Week for the past quarter, with return rate percentages.                            | custom_measures_ga4.npi_first_visits, custom_measures_ga4.npi_returning_visits, hcp365_core.week                                           | hcp365_core.day                          | 90 days ago for 90 days   | hcp365_core.week asc                              | 13    |
      | 561973     | 5590          | 69431   | Show NPI Pageviews by Page URL grouped by Primary Specialty for the last 45 days to assess topic affinity.                           | hcp365_core.normalizedurl, npi_reference.primary_specialty,resolved_measures.npi_pageviews                                                 | hcp365_core.day                          | last 45 days              | resolved_measures.npi_pageviews desc              | 500   |
      | 561973     | 5590          | 69431   | Show UTM Term performance (Identified NPIs and NPI Events) by Campaign Name for brand-level paid search in Q1.                       | hcp365_core.utm_term, resolved_dimensions.campaign_name, resolved_measures.distinct_npis, resolved_measures.npi_events                     | hcp365_core.day, hcp365_core.source_type | this year Q1, PAID SEARCH | resolved_measures.distinct_npis desc              | 500   |
      | 561973     | 5590          | 69431   | Show NPI Social Impressions and NPI Social Clicks by Channel and Week for the past 8 weeks.                                          | hcp365_core.tokentype, hcp365_core.week, resolved_measures.npi_social_impressions, resolved_measures.npi_social_clicks                     | hcp365_core.day                          | 56 days ago for 56 days   | hcp365_core.week desc                             | 500   |
      | 561973     | 5590          | 69431   | Which Collection ID values have Identified NPIs / Total Events ratio < 20% but high Total Events volume, grouped by Advertiser Name? | resolved_dimensions.token, resolved_dimensions.advertiser_name, resolved_measures.distinct_npis, resolved_measures.total_events            |                                          |                           | resolved_measures.total_events desc               | 500   |
      | 561973     | 5590          | 69431   | Provide HCP First Visits vs HCP Returning Visits by User Type and Day of Week.                                                       | resolved_dimensions.user_type, hcp365_core.dayofweek, custom_measures_ga4.hcp_first_visits, custom_measures_ga4.hcp_returning_visits       |                                          |                           | custom_measures_ga4.hcp_first_visits desc         | 500   |
      | 562262     | 629           | 69431   | Show me Total Pageviews and Total Events by Day for the last 30 days                                                                 | hcp365_core.day, resolved_measures.pageviews_measure, resolved_measures.total_events                                                       | hcp365_core.day                          | last 30 days              | hcp365_core.day asc                               | 500   |
      | 562262     | 629           | 69431   | Display Total Active Users and Total Returning Visits by Day of Week                                                                 | hcp365_core.dayofweek, custom_measures_ga4.active_user_count_, custom_measures_ga4.returning_visits                                        |                                          |                           | custom_measures_ga4.active_user_count_ desc       | 500   |
      | 562262     | 629           | 69431   | Show HCP Media CTR and HCP Social Impressions by Month for last 90 days                                                              | hcp365_core.month, resolved_measures.hcp_media_ctr, resolved_measures.hcp_social_impressions                                               | hcp365_core.day                          | last 90 days              | hcp365_core.month asc                             | 500   |
      | 562262     | 629           | 69431   | What are NPI Visits and NPI First Visits by Week?                                                                                    | hcp365_core.week, custom_measures_ga4.npi_visits, custom_measures_ga4.npi_first_visits                                                     |                                          |                           | hcp365_core.week desc                             | 500   |
      | 562262     | 629           | 69431   | Show Hours and Minutes spent by Weekday-Weekend                                                                                      | hcp365_core.weekday_weekend, bi_hcp365_time_spent.time_spent_hrs, bi_hcp365_time_spent.time_spent_min                                      |                                          |                           | bi_hcp365_time_spent.time_spent_hrs desc          | 500   |
      | 562262     | 629           | 69431   | What are Total Media Impressions and Total Media Clicks by Channel?                                                                  | hcp365_core.tokentype, resolved_measures.ad_impressions_measure, resolved_measures.ad_clicks_measure                                       |                                          |                           | resolved_measures.ad_impressions_measure desc     | 500   |
      | 562262     | 629           | 69431   | Show HCP Events and HCP Email Opens grouped by Advertiser Name                                                                       | resolved_dimensions.advertiser_name, resolved_measures.hcp_events, resolved_measures.hcp_email_opens                                       |                                          |                           | resolved_measures.hcp_events desc                 | 500   |
      | 562262     | 629           | 69431   | Display NPI Pageviews and Identified NPIs by Collection Name                                                                         | resolved_dimensions.collection_name, resolved_measures.npi_pageviews, resolved_measures.distinct_npis                                      |                                          |                           | resolved_measures.npi_pageviews desc              | 500   |
      | 562262     | 629           | 69431   | Show HCP Visits and HCP Pageviews by Primary Specialty                                                                               | npi_reference.primary_specialty, custom_measures_ga4.hcp_visits, resolved_measures.hcp_pageviews                                           |                                          |                           | custom_measures_ga4.hcp_visits desc               | 500   |
      | 562262     | 629           | 69431   | Show Identified NPIs and NPI Media Impressions by Hospital Affiliation                                                               | npi_facility_association_aggregation.hospital, resolved_measures.distinct_npis, resolved_measures.npi_ad_impressions                       |                                          |                           | resolved_measures.distinct_npis desc              | 500   |
      | 562262     | 629           | 69431   | Display Total Form Submissions and Total Form Starts by Profession                                                                   | npi_reference.profession, custom_measures_ga4.count_form_submitted, custom_measures_ga4.count_form_started                                 |                                          |                           | custom_measures_ga4.count_form_submitted desc     | 500   |
      | 562262     | 629           | 69431   | What are HCP Form Submissions and HCP File Downloads by Secondary Specialty?                                                         | npi_reference.secondary_specialty, custom_measures_ga4.hcp_count_form_submitted, custom_measures_ga4.hcp_count_downloads                   |                                          |                           | custom_measures_ga4.hcp_count_form_submitted desc | 500   |
      | 562262     | 629           | 69431   | Display Total Events and Total Active Users grouped by Page Domain                                                                   | resolved_dimensions.to_url_domain, resolved_measures.total_events, custom_measures_ga4.active_user_count_                                  |                                          |                           | resolved_measures.total_events desc               | 500   |
      | 562262     | 629           | 69431   | Show NPI Email Opens and NPI Social Clicks by Source Type                                                                            | hcp365_core.source_type, resolved_measures.npi_email_opens, resolved_measures.npi_social_clicks                                            |                                          |                           | resolved_measures.npi_email_opens desc            | 500   |
      | 562262     | 629           | 69431   | What are Total Social Impressions and Total Social Clicks by Social Provider?                                                        | hcp365_core.social_provider, resolved_measures.social_impressions_measure, resolved_measures.social_clicks_measure                         |                                          |                           | resolved_measures.social_impressions_measure desc | 500   |
      | 562262     | 629           | 69431   | Show HCP Search Clicks and HCP Avg. Engagement Time (sec) by Attributed Source                                                       | resolved_dimensions.attributed_source, resolved_measures.hcp_search_clicks, custom_measures_ga4.hcp_average_engagement_time_               |                                          |                           | resolved_measures.hcp_search_clicks desc          | 500   |
      | 562262     | 629           | 69431   | Show NPI Media Impressions and NPI Media Clicks by Campaign Name                                                                     | resolved_dimensions.campaign_name, resolved_measures.npi_ad_impressions, resolved_measures.npi_ad_clicks                                   |                                          |                           | resolved_measures.npi_ad_impressions desc         | 500   |
      | 562262     | 629           | 69431   | Show Total Video Starts and Total Video Completes by Creative Type                                                                   | hcp365_core.creativetype, custom_measures_ga4.video_starts, custom_measures_ga4.video_completes                                            |                                          |                           | custom_measures_ga4.video_starts desc             | 500   |
      | 562262     | 629           | 69431   | Display HCP Media Clicks and HCP Media CTR by Ad Type                                                                                | hcp365_core.ad_type, resolved_measures.hcp_ad_clicks, resolved_measures.hcp_media_ctr                                                      |                                          |                           | resolved_measures.hcp_ad_clicks desc              | 500   |
      | 562262     | 629           | 69431   | What are Total Search Clicks and Total Email Clicks by Keyword?                                                                      | resolved_dimensions.search_term, resolved_measures.search_clicks_measure, resolved_measures.email_clicks_measure                           |                                          |                           | resolved_measures.search_clicks_measure desc      | 500   |
      | 562262     | 629           | 69431   | Show Total Search Clicks and Total Email Opens by DS Campaign                                                                        | hcp365_core.dscampaign, resolved_measures.search_clicks_measure, resolved_measures.email_opens_measure                                     |                                          |                           | resolved_measures.search_clicks_measure desc      | 500   |
      | 562262     | 629           | 69431   | Display NPI Search Clicks and NPI Events by DS Ad Group                                                                              | resolved_dimensions.dsadgroup, resolved_measures.npi_search_clicks, resolved_measures.npi_events                                           |                                          |                           | resolved_measures.npi_search_clicks desc          | 500   |
      | 562262     | 629           | 69431   | What are HCP Search Clicks and HCP Events by DS Search Term?                                                                         | hcp365_core.dssearchterm, resolved_measures.hcp_search_clicks, resolved_measures.hcp_events                                                |                                          |                           | resolved_measures.hcp_search_clicks desc          | 500   |
      | 562262     | 629           | 69431   | What are Total Form Submissions and Total First Visits by UTM Source?                                                                | hcp365_core.utm_source, custom_measures_ga4.count_form_submitted, custom_measures_ga4.first_visits                                         |                                          |                           | custom_measures_ga4.count_form_submitted desc     | 500   |
      | 562262     | 629           | 69431   | Show HCP Pageviews and HCP Active Users by UTM Campaign                                                                              | hcp365_core.utm_campaign, resolved_measures.hcp_pageviews, custom_measures_ga4.hcp_active_user_count_                                      |                                          |                           | resolved_measures.hcp_pageviews desc              | 500   |
      | 562262     | 629           | 69431   | Display NPI Form Starts and NPI Form Submissions by UTM Medium                                                                       | hcp365_core.utm_medium, custom_measures_ga4.npi_count_form_started, custom_measures_ga4.npi_count_form_submitted                           |                                          |                           | custom_measures_ga4.npi_count_form_started desc   | 500   |
      | 562262     | 629           | 69431   | Show HCP Email Clicks and HCP Form Starts grouped by Param 1                                                                         | hcp365_core.param1, resolved_measures.hcp_email_clicks, custom_measures_ga4.hcp_count_form_started                                         |                                          |                           | resolved_measures.hcp_email_clicks desc           | 500   |
      | 562262     | 629           | 69431   | Display Total File Downloads and Total Engaged Sessions per User by Param 3                                                          | hcp365_core.param3, custom_measures_ga4.count_downloads, custom_measures_ga4.engaged_sessions_per_user                                     |                                          |                           | custom_measures_ga4.count_downloads desc          | 500   |
      | 562262     | 629           | 69431   | What are NPI Video Starts and NPI Video Completes by Param 5?                                                                        | hcp365_core.param5, custom_measures_ga4.npi_video_starts, custom_measures_ga4.npi_video_completes                                          |                                          |                           | custom_measures_ga4.npi_video_starts desc         | 500   |
      | 562262     | 629           | 69431   | Display NPI Visits and NPI Active Users by Device Type                                                                               | resolved_dimensions.devicetype, custom_measures_ga4.npi_visits, custom_measures_ga4.npi_active_user_count_                                 |                                          |                           | custom_measures_ga4.npi_visits desc               | 500   |
      | 562262     | 629           | 69431   | Show Total Pageviews and Total Media Impressions by OS                                                                               | hcp365_core.os, resolved_measures.pageviews_measure, resolved_measures.ad_impressions_measure                                              |                                          |                           | resolved_measures.pageviews_measure desc          | 500   |
      | 562262     | 629           | 69431   | What are HCP Unique Sessions and HCP Engaged Sessions per User by Device Type?                                                       | resolved_dimensions.devicetype, custom_measures_ga4.hcp_unique_sessions, custom_measures_ga4.hcp_engaged_sessions_per_user                 |                                          |                           | custom_measures_ga4.hcp_unique_sessions desc      | 500   |
      | 562262     | 629           | 69431   | Show Total Events and Total Visits by Channel and Day                                                                                | hcp365_core.tokentype, hcp365_core.day, resolved_measures.total_events, custom_measures_ga4.visits                                         |                                          |                           | resolved_measures.total_events desc               | 500   |
      | 562262     | 629           | 69431   | Display Identified NPIs and NPI Media Frequency by Campaign Name and Month                                                           | resolved_dimensions.campaign_name, hcp365_core.month, resolved_measures.distinct_npis, resolved_measures.avg_npi_media_frequency           |                                          |                           | resolved_measures.distinct_npis desc              | 500   |
      | 562262     | 629           | 69431   | Show HCP Visits and Avg. Video Progress by Primary Specialty and Device Type                                                         | npi_reference.primary_specialty, resolved_dimensions.devicetype, custom_measures_ga4.hcp_visits, custom_measures_ga4.average_video_percent |                                          |                           | custom_measures_ga4.hcp_visits desc               | 500   |
