browser=chrome
headless=false
timeout=60

demoURL=https://platform-demo.pulsepoint.com/AccountMgmt/LifeLogin.aspx
demoUser=admin11
demoPassword=ppadmin1

preReleaseURL=https://platform-prerelease.pulsepoint.com/AccountMgmt/LifeLogin.aspx
preReleaseUser=test123
preReleasePassword=pass123